//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 02:06:14 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://amw.gdynia.pl/sao/lab1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.tkaczyk.soaplab1script;
